spring.datasource.url=${DB_URL:jdbc:mysql://databasep2p.mysql.database.azure.com/development_gmtbfs?createDatabaseIfNotExist=true&useSSL=true&requireSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:p2padmin@databasep2p}
spring.datasource.password=${DB_PASSWORD:p2P@dmin}
email.subject.prefix=[DEV]
zoho.payments.redirect.url=https://p2pv1dev-ana9azfph7chftea.centralindia-01.azurewebsites.net
zoho.webhook.signing-key=c17d8297dbe1ca9d972ed5bfafd4359125cb983d7d71f37b0ea96b0d172569f41eac4f722a702bb3cca2d6a1389d257055123d33228e8e0c71773317e90c0c8682801cd02798181e375bd7387bc908b5