spring.datasource.url=jdbc:mysql://qua.mysql.database.azure.com/quaproduction?createDatabaseIfNotExist=true&euseSSL=true&requireSSL=false&serverTimezone=UTC
spring.datasource.username=quauser
spring.datasource.password=F3pfg7u8t2z1
email.subject.prefix=
zoho.payments.redirect.url=https://qua.procucev.com