#spring.profiles.active=dev
spring.application.name=procucev
spring.datasource.hikari.pool-name=procucev pool
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jackson.serialization.fail-on-empty-beans=false
##Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.password=Pr0cucevP@TE$
spring.mail.password=dzbpyhqdelqdmcgt
spring.mail.username=notifications@procucev.com
spring.mail.phone=8747846972
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smpt.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.smtp.socketFactory.class= javax.net.ssl.SSLSocketFactory
spring.mail.properties.smtp.socketFactory.port:465
spring.mail.properties.mail.smtp.ssl.trust = smtp.gmail.com
logging.level.org.springframework.security=DEBUG
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
mailFrom=Procucev Admin
host=https://qua.procucev.com/
CLIENT_ACCESS_TOKEN_VALIDTY=7200
CLIENT_REFRESH_TOKEN_VALIDTY=7200
mailid=invitations@procucev.com
#mailPassword=Pr0cuc3v@202$
mailPassword=uqdylqothagsvqlg
#mailPassword=yjvcnltcpxbcvviu
toAddress=srinivas.mukku@procucev.com
quaemail=gmtrfq@procucev.com
quapassword=xgrlprdmetvsbite
app.oauth2.client-id=procucev
app.oauth2.client-secret=secret123
spring.main.allow-bean-definition-overriding=true
server.servlet.context-path=/procucev
jobs.enabled=true
sms.api.url=https://sms.sendmsg.in/datasend
sms.api.authkey=UHJvY3VjZXZfT1RQOlR6bHp5TWNGRVpSRg==
# Zoho OAuth details
zoho.client.id=YOUR_CLIENT_ID
zoho.client.secret=YOUR_CLIENT_SECRET
zoho.refresh.token=YOUR_REFRESH_TOKEN
zoho.refresh.url=https://accounts.zoho.com/oauth/v2/token
jwt.secret: mySuperSecretKeyThatIsAtLeast32CharsLong
