spring.datasource.url=jdbc:mysql://qua.mysql.database.azure.com/quaproduction?createDatabaseIfNotExist=true&euseSSL=true&requireSSL=false&serverTimezone=UTC
spring.datasource.username=quauser
spring.datasource.password=F3pfg7u8t2z1
email.subject.prefix=
zoho.payments.redirect.url=https://qua.procucev.com
zoho.webhook.signing-key=3b9850e4c06fc01b0281a297c2a7a0a739a2d93e9fe3aa93d0a3d936583269ff29487e9a1d25011f8c95639f074b10c67f28d8a7b9957fef20dd86925bb35da42a14a00103a31ebbdb0ac0565fb33d17