package com.portal.procucev.controller;

import java.util.Map;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.portal.procucev.customexception.MessageResponse;
import com.portal.procucev.customexception.RfqDocumentSizeExceededException;
import com.portal.procucev.dao.OrgDao;
import com.portal.procucev.dao.UserDao;
import com.portal.procucev.model.Rfq;
import com.portal.procucev.model.User;
import com.portal.procucev.service.AutomaticRfqService;
import com.portal.procucev.utils.ApplicationConstants;
import com.portal.procucev.utils.StatusCodes;

@RestController
@RequestMapping("/automate")
public class AutomaticRfqCreationController {

	public static final Logger logger = LoggerFactory.getLogger(AutomaticRfqCreationController.class);

	@Autowired
	AutomaticRfqService autoRfqService;

	@Autowired
	UserDao userDao;
	
	@Autowired
	OrgDao orgDao;

	@PostMapping("/raiseRfq")
	public ResponseEntity<?> raiseRfqAuto(@RequestBody Rfq rfq) {

	    Optional<User> userOpt = userDao.findById(rfq.getUser());

	    if (!userOpt.isPresent()) {
	        return ResponseEntity.badRequest().body("User not found");
	    }

	    User user = userOpt.get();

	    // Delegated to the service so the email-to-RFQ pipeline resolves a partial delivery address
	    // through exactly the same pincode/organisation fallbacks this endpoint uses.
	    autoRfqService.resolveDeliveryLocation(rfq, user);

	    // IDs are generated by the service rather than accepted from an HTTP request.
	    rfq.setRfqId(autoRfqService.generateRfqId("RFQ"));

	    boolean response;
	    try {
	        response = autoRfqService.raiseRfq(rfq);
	    } catch (RfqDocumentSizeExceededException e) {
	        logger.warn("RFQ rejected for oversized document: {}", e.getMessage());
	        MessageResponse sizeResponse = new MessageResponse(
	                StatusCodes.CLIENT_PR_CLOSED_code,
	                e.getMessage(),
	                null,
	                String.valueOf(ApplicationConstants.FAILURE));
	        return new ResponseEntity<>(sizeResponse, HttpStatus.PAYLOAD_TOO_LARGE);
	    }

	    String statusCode = response
	            ? String.valueOf(ApplicationConstants.SUCCESS)
	            : String.valueOf(ApplicationConstants.FAILURE);

	    String msg = response
	            ? String.format(ApplicationConstants.RFQ_CREATED_SUCCESS, "")
	            : String.format(ApplicationConstants.RFQ_CREATED_FAILURE, "");

	    MessageResponse responseObj = new MessageResponse(
	            StatusCodes.CLIENT_PR_CLOSED_code,
	            msg,
	            null,
	            statusCode);

	    return new ResponseEntity<>(responseObj, HttpStatus.OK);
	}

	@PostMapping("/validateEmail")
	public ResponseEntity<?> validateEmail(@RequestParam String email) {

		logger.info("Email Id : {}", email);
		Map<String, String> response = autoRfqService.validateEmail(email);

		return ResponseEntity.ok(response);
	}

}
