onnected!
2026-07-31T06:05:01.9689234Z    _|_|
2026-07-31T06:05:01.9690495Z  _|    _|  _|_|_|_|  _|    _|  _|  _|_|    _|_|
2026-07-31T06:05:01.9690531Z  _|_|_|_|      _|    _|    _|  _|_|      _|_|_|_|
2026-07-31T06:05:01.9690551Z  _|    _|    _|      _|    _|  _|        _|
2026-07-31T06:05:01.9690569Z  _|    _|  _|_|_|_|    _|_|_|  _|          _|_|_|
2026-07-31T06:05:01.9690589Z
2026-07-31T06:05:01.9690613Z      J A V A   O N   A P P   S E R V I C E
2026-07-31T06:05:01.9690629Z
2026-07-31T06:05:01.9690667Z Documentation: https://aka.ms/appservice
2026-07-31T06:05:01.9690686Z
2026-07-31T06:05:01.9690718Z **NOTE**: No files or system changes outside of /home will persist beyond your application's current session. /home is your application's persistent storage and is shared across all the server instances.
2026-07-31T06:05:01.9690737Z
2026-07-31T06:05:01.9690752Z
2026-07-31T06:05:02.0072958Z Determined OS to be: ubuntu
2026-07-31T06:05:02.0082809Z Updating /etc/ssh/sshd_config to use PORT 2222
2026-07-31T06:05:02.0186586Z Starting ssh service...
2026-07-31T06:05:02.2887299Z ssh-keygen: generating new host keys: DSA
2026-07-31T06:05:02.49146Z  * Starting OpenBSD Secure Shell server sshd
2026-07-31T06:05:02.6325002Z    ...done.
2026-07-31T06:05:02.8235977Z  * sshd is running
2026-07-31T06:05:02.841586Z ## Printing build info...
2026-07-31T06:05:02.8525668Z                                            PACKAGE |                             VERSION | COMMIT
2026-07-31T06:05:02.852598Z        Microsoft.AppService.WebsitesExtensionsJava |                        1.0.03290234 | ae284a4
2026-07-31T06:05:02.8526007Z                                               self |                        1.0.03296336 | 76247a61
2026-07-31T06:05:02.8541258Z ## Done printing build info.
2026-07-31T06:05:02.874429Z Container info: WEBSITE_INSTANCE_ID = 875718e1259d0c5a09934897b0628f9308c82d8ef05f4c352f549fa07f7ace8b ; WEBSITE_SITE_NAME = qua-backend-prod
2026-07-31T06:05:02.9129382Z Add public certificates to keystore if exists...
2026-07-31T06:05:02.9135784Z Add private certificates to keystore if exists...
2026-07-31T06:05:02.9143532Z Configuring max heap = 1299 MB
2026-07-31T06:05:02.9747915Z STARTUP_FILE=
2026-07-31T06:05:02.9751409Z STARTUP_COMMAND=java -jar /home/site/wwwroot/procucev-0.0.1-SNAPSHOT.war
2026-07-31T06:05:02.9754353Z No STARTUP_FILE available.
2026-07-31T06:05:02.9827929Z Running STARTUP_COMMAND: java -jar /home/site/wwwroot/procucev-0.0.1-SNAPSHOT.war
2026-07-31T06:05:02.9829937Z
2026-07-31T06:05:03.0266577Z Picked up JAVA_TOOL_OPTIONS: -javaagent:/agents/java/applicationinsights-agent-codeless.jar
2026-07-31T06:05:03.7472265Z OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2026-07-31T06:05:07.3771317Z 2026-07-31 06:05:07.357Z INFO  c.m.a.a.i.c.ConfigurationBuilder - Some telemetry may be sampled out because a default sampling configuration was added in version 3.4.0 to reduce the default billing cost. You can set the sampling configuration explicitly: https://learn.microsoft.com/azure/azure-monitor/app/java-standalone-config#sampling
2026-07-31T06:05:15.143128Z 2026-07-31 06:05:15.140Z WARN  i.o.s.a.ResourceConfiguration - Found reference to io.opentelemetry.sdk.autoconfigure.internal.EnvironmentResourceProvider in otel.java.enabled.resource.providers. Please update to io.opentelemetry.sdk.autoconfigure.EnvironmentResourceProvider. Support for the old provider name will be removed after 1.49.0.
2026-07-31T06:05:27.5542578Z 2026-07-31 06:05:27.523Z INFO  c.m.applicationinsights.agent - Application Insights Java Agent 3.7.3 started successfully (PID 40, JVM running for 24.498 s)
2026-07-31T06:05:27.5550678Z 2026-07-31 06:05:27.554Z INFO  c.m.applicationinsights.agent - Java version: 17.0.17, vendor: Microsoft, home: /usr/lib/jvm/msopenjdk-17-amd64
2026-07-31T06:05:33.2269225Z Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2026-07-31T06:05:43.5206906Z
2026-07-31T06:05:43.5291088Z   .   ____          _            __ _ _
2026-07-31T06:05:43.5291392Z  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
2026-07-31T06:05:43.5291492Z ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2026-07-31T06:05:43.5291591Z  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
2026-07-31T06:05:43.5291612Z   '  |____| .__|_| |_|_| |_\__, | / / / /
2026-07-31T06:05:43.529163Z  =========|_|==============|___/=/_/_/_/
2026-07-31T06:05:43.5291646Z
2026-07-31T06:05:43.5302915Z  :: Spring Boot ::                (v3.5.0)
2026-07-31T06:05:43.5305429Z
2026-07-31T06:05:45.4705014Z 2026-07-31T06:05:45.256Z  INFO 40 --- [procucev] [           main] c.portal.procucev.ProcucevApplication    : Starting ProcucevApplication v0.0.1-SNAPSHOT using Java 17.0.17 with PID 40 (/home/site/wwwroot/procucev-0.0.1-SNAPSHOT.war started by root in /)
2026-07-31T06:05:45.4818929Z 2026-07-31T06:05:45.481Z  INFO 40 --- [procucev] [           main] c.portal.procucev.ProcucevApplication    : The following 1 profile is active: "prod"
2026-07-31T06:05:57.4951026Z 2026-07-31T06:05:57.487Z  INFO 40 --- [procucev] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2026-07-31T06:05:59.2169147Z 2026-07-31T06:05:59.216Z  INFO 40 --- [procucev] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 1616 ms. Found 29 JPA repository interfaces.
2026-07-31T06:06:11.5357145Z 2026-07-31T06:06:11.525Z  INFO 40 --- [procucev] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2026-07-31T06:06:11.9264379Z 2026-07-31T06:06:11.926Z  INFO 40 --- [procucev] [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2026-07-31T06:06:11.9356719Z 2026-07-31T06:06:11.935Z  INFO 40 --- [procucev] [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.41]
2026-07-31T06:06:12.9245892Z 2026-07-31T06:06:12.924Z  INFO 40 --- [procucev] [           main] o.a.c.c.C.[.[localhost].[/procucev]      : Initializing Spring embedded WebApplicationContext
2026-07-31T06:06:12.9327657Z 2026-07-31T06:06:12.932Z  INFO 40 --- [procucev] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 26666 ms
2026-07-31T06:06:12.9544187Z Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2026-07-31T06:06:16.0007955Z 2026-07-31T06:06:15.990Z  INFO 40 --- [procucev] [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2026-07-31T06:06:17.3589385Z 2026-07-31T06:06:17.358Z  INFO 40 --- [procucev] [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.6.15.Final
2026-07-31T06:06:26.3564492Z 2026-07-31T06:06:26.338Z  INFO 40 --- [procucev] [           main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
2026-07-31T06:06:30.6711676Z 2026-07-31T06:06:30.652Z  INFO 40 --- [procucev] [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2026-07-31T06:06:31.0631391Z 2026-07-31T06:06:31.062Z  INFO 40 --- [procucev] [           main] com.zaxxer.hikari.HikariDataSource       : procucev pool - Starting...
2026-07-31T06:06:34.97356Z 2026-07-31T06:06:34.972Z  WARN 40 --- [procucev] [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1045, SQLState: 28000
2026-07-31T06:06:34.9780673Z 2026-07-31T06:06:34.977Z ERROR 40 --- [procucev] [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Access denied for user 'quause'@'20.187.184.128' (using password: YES)
2026-07-31T06:06:35.067585Z 2026-07-31T06:06:34.987Z  WARN 40 --- [procucev] [           main] o.h.e.j.e.i.JdbcEnvironmentInitiator     : HHH000342: Could not obtain connection to query metadata
2026-07-31T06:06:35.0676311Z
2026-07-31T06:06:35.0676354Z org.hibernate.exception.GenericJDBCException: unable to obtain isolated JDBC connection [Access denied for user 'quause'@'20.187.184.128' (using password: YES)] [n/a]
2026-07-31T06:06:35.067638Z 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676405Z 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676508Z 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676534Z 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcIsolationDelegate.delegateWork(JdbcIsolationDelegate.java:116) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.067656Z 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:336) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676585Z 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:129) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676609Z 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:81) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676653Z 	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676678Z 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676703Z 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676726Z 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676748Z 	at org.hibernate.boot.model.relational.Database.<init>(Database.java:45) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676788Z 	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:226) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676812Z 	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:194) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676847Z 	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:171) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676873Z 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1442) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676913Z 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1513) ~[hibernate-core-6.6.15.Final.jar!/:6.6.15.Final]
2026-07-31T06:06:35.0676939Z 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66) ~[spring-orm-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0676964Z 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:390) ~[spring-orm-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0676988Z 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:419) ~[spring-orm-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677011Z 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:400) ~[spring-orm-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677052Z 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:366) ~[spring-orm-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677226Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1873) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677254Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1822) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677279Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:607) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.067732Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677344Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677367Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677389Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677437Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677481Z 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:365) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677506Z 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:135) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.067753Z 	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:691) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677553Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:513) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677594Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1375) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677653Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1205) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677677Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:569) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.06777Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677741Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677766Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677788Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.067781Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677833Z 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:365) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677876Z 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:135) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677901Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1725) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677925Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1474) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0677948Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:606) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678002Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678046Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.067807Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678092Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678114Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678137Z 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678177Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1740) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.06782Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1628) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678224Z 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:913) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678247Z 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.067827Z 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:240) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678311Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1395) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678336Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678359Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:569) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678385Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678428Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678453Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678475Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678512Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678536Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1682) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678559Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1628) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678584Z 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:785) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678626Z 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:768) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.067865Z 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:146) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678675Z 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:509) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678699Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1459) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678751Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:606) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678793Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678817Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678842Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678864Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.7.jar!/:6.2.7]
2026-07-31T06:06:35.0678887Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.7.jar!/:6.2.7]# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - p2pv1servicesdev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install -DskipTests -Dspring.profiles.active=test

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_787984C7797A4B56B48A20E919584B0D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DF7E5227708F4DA98C575D31D86EFDA6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EA304D286C98485B84A6FDFD85544021 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'p2pv1servicesdev'
          slot-name: 'Production'
          package: '*.war'
          


